---
- name: Environment configuration
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: ping-pong, tags: ["ping-pong"] }
    - { role: docker, tags: ["docker"] }
    - { role: terraform, tags: ["terraform"] }
    - { role: postgres-client, tags: ["postgres-client"] }
